"""initial 7-table schema with audit columns

Revision ID: 8f0b303593ff
Revises: 
Create Date: 2026-04-24 08:07:31.606059+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f0b303593ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('manager_name', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'code', name='uq_area_store_code')
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_store_id'), ['store_id'], unique=False)

    op.create_table('entrances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entrances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrances_store_id'), ['store_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('placement_x', sa.Float(), nullable=False),
    sa.Column('placement_y', sa.Float(), nullable=False),
    sa.Column('qr_code_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_store_id'), ['store_id'], unique=False)

    op.create_table('visitor_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('anon_id', sa.String(length=64), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stay_seconds', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('age_group', sa.String(length=8), nullable=False),
    sa.Column('companion_count', sa.Integer(), nullable=False),
    sa.Column('entrance_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=True),
    sa.Column('full_body_url', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('interested_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entrance_id'], ['entrances.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_sessions_anon_id'), ['anon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_sessions_entered_at'), ['entered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_sessions_store_id'), ['store_id'], unique=False)

    op.create_table('behavior_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('behavior_type', sa.String(length=32), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['visitor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('behavior_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavior_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_events_started_at'), ['started_at'], unique=False)

    op.create_table('visitor_positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['visitor_sessions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor_positions', schema=None) as batch_op:
        batch_op.create_index('ix_visitor_positions_session_t', ['session_id', 't'], unique=False)
        batch_op.create_index('ix_visitor_positions_store_t', ['store_id', 't'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_visitor_positions_store_t')
        batch_op.drop_index('ix_visitor_positions_session_t')

    op.drop_table('visitor_positions')
    with op.batch_alter_table('behavior_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavior_events_started_at'))
        batch_op.drop_index(batch_op.f('ix_behavior_events_session_id'))

    op.drop_table('behavior_events')
    with op.batch_alter_table('visitor_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_sessions_store_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_sessions_entered_at'))
        batch_op.drop_index(batch_op.f('ix_visitor_sessions_anon_id'))

    op.drop_table('visitor_sessions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_store_id'))

    op.drop_table('products')
    with op.batch_alter_table('entrances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrances_store_id'))

    op.drop_table('entrances')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_store_id'))

    op.drop_table('areas')
    op.drop_table('stores')
    # ### end Alembic commands ###
